### ISSUE TITLE
after takeoff,drone keep rising

### ISSUE THREAD

**Issue by wraysx** [tum-vision/tum_simulator#12]
Hi all,
   i am using ros kinetic and gazebo8, and install ardrone_autonomy and tum_simulator.
   but after i pub the message to /ardrone/takeoff, the drone rises and keeps rising even i pub the cmd_vel with z = -1,which means flying to the ground with the max speed, but i still rises, am i missing something? the gravity is -9.8

**Comment by wraysx** [comment]
i found the reason.
i am using the quadrotor with other sensors, but i just change the spawn_quadrotor.launch, it is the quadrotor_sensors.urdf.xacro file matters, which means i should add  the sensors into this files to make it right.
maybe it is these three lines matters.
<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
xmlns:xacro="http://ros.org/wiki/xacro">

**Comment by plakato** [comment]
Hi @raywang-nx ,
I have the same problem. What sensors are you using and how does your quadrotor_sensors.urdf.xacro file look?

**Comment by wraysx** [comment]
@plakato Sorry for being so late ...
it is such a easy file.


<?xml version="1.0"?>

<robot name="quadrotor" xmlns:xacro="http://www.ros.org/wiki/xacro">
   
    <xacro:property name="M_PI" value="3.1415926535897931" />
    
    
    <xacro:include filename="$(find cvg_sim_gazebo)/urdf/quadrotor.urdf.xacro" />
    
    
    
    <xacro:include filename="$(find hector_sensors_description)/urdf/realsense_camera.urdf.xacro" />
    <xacro:realsense_camera name="camera" parent="base_link">
      <origin xyz="0.2 0.0 0.1" rpy="0 0 0"/>
    </xacro:realsense_camera>
    
</robot>

**Comment by plakato** [comment]
Thank you @raywang-nx, 

I have already solved my problem by installing some hector_quadrotor packages that were dealing with sensors..
